### ISSUE TITLE
Web GUI without Internet

### ISSUE THREAD

**Issue by HBerecz** [kolinger/rd-usb#13]
I downloaded http://127.0.0.1:5000 with WinHTTrack to D:/3/UM25C/127.0.0.1_5000 on my PC because I wold like to adapt your excellent program to my special wishes.
But the adaption of web.py from 'url = "http://127.0.0.1:%s" % port' to 'url = "D:/3/UM25C/127.0.0.1_5000"' did not work.
Could you help me to make it function? Thank you.

**Comment by kolinger** [comment]
Hello, this will not work but I don't think you need this anyway.

This app doesn't use internet. It requires webserver but this webserver runs locally on your computer. You can disconnect your PC from everything and it should work just fine.

WinHTTrack is used to create snapshot of website but there is no point of doing that here. Since 127.0.0.1 is your computer. You don't need to save this URL to your HDD. It's already on your HDD!

Why you doing this? Can you please explain your goal so I can provide more helpful response?

**Comment by HBerecz** [comment]
Hello, thank you for your quick response.

I would like to make some minor changes in the layout, e.g. colors of the graph and Left axis = Current, Right axis = Voltage as default.

By the way: how can I empty the Log and Data tables and force that the Graph window is cacelled and start new?

**Comment by kolinger** [comment]
Then it's easiest to adjust CSS files found in `static/css` directory and JS files found `static/js` directory also HTML in `webapp/templates`. No need for HTTrack. Just explore files and you should find anything you need.

If you want to reset everything then delete data directory. On Windows you can find data directory in `C:\Users\username\AppData\Local\rd-usb` where username is name of your account. Just delete whole rd-usb directory. It will be created again on next startup. In this directory there is file `data.db` where log and data is stored. It's SQLite database and you can open this database with some database explorer program and then you can manipulate data as you want.

**Comment by HBerecz** [comment]
Hello, thank you for your quick response.

I made some minor changes in the layout and colors of the Graph (Voltage = blue, Current = red according to the German conventions) in the \webapp\templates\layout.html and \static\js\application.js

**Comment by kolinger** [comment]
I didn't even know there is such convention. Default colors were chosen randomly. 

More accurate and more colors can be useful for everyone. I would like to assign each unit unique color to improve distinction between units. Do you have idea what colors to use for other units? Like for power, temperature, current/power over time and resistance? I didn't find any convention.

![Screenshot_1](https://user-images.githubusercontent.com/1590930/131825218-0222f363-dd4b-4538-9c82-025e1628fe49.png)

What do you think about these colors? Blue for voltage, red for current, green for power, dark yellow for temperature, dark blue for current over time, dark green for power over time and violet for resistance.

**Comment by HBerecz** [comment]
I think, this is a good idea. My favorite colors are:

Blue for voltage
red for current
green for resistance
dark yellow for power
dark blue for power over time
dark green for temperature
violet for current over time

By the way: perhaps it would be helpul for reading the Graph if the Left axis/Right axis Skale values are of the same color as the vertical descriptions and these are of the same font-size as those.

**Comment by kolinger** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/1590930/131894251-3581ec70-8b2e-4870-b30c-1b361b69887c.png)
![Screenshot_1](https://user-images.githubusercontent.com/1590930/131894252-e3098b35-1cc1-42df-8a4f-20edb71b2048.png)
![Screenshot_2](https://user-images.githubusercontent.com/1590930/131894254-ed964a1b-8bfb-4765-bfff-b92e5abe1dc6.png)
![Screenshot_3](https://user-images.githubusercontent.com/1590930/131894255-b06bbb46-2540-4588-9c2e-d00bf5d6aa90.png)

What you think?

**Comment by HBerecz** [comment]
It's fantastic! When can I download the new version?

**Comment by kolinger** [comment]
You can find it [here](https://github.com/kolinger/rd-usb/releases). So is this issue resolved then? If you have other suggestions that are beneficial to all users, let me know (as new issue).

**Comment by Razor512** [comment]
Off topic, but I wanted to say thanks for making such an amazing application. 
One way that I have been using it to examine strange behaviors in some charge controllers, is to sync up values with other sources (K type thermal probes), as well as video or a charging status display.

While I am still working figuring out how to do a reliable macro for it, (trying to automate setting an offset based on the accumulated time in the skipped rows, as well as any any accumulated power related info so that there is a 0 starting point for the desired data, and then formatting the offset time values to hh:mm:ss. That then allows for easy creating of a video excerpt/ visualization of what is happening exactly when charging behavior changes. If I get a script working reliable for excel, I will try to find a place to share it :).

![excelstuff](https://user-images.githubusercontent.com/75226214/132056834-1ce6efd6-48ac-4379-abad-8bd0599a4811.jpg)

**Comment by kolinger** [comment]
You need column where is relative time from beginning in regular hh:mm:ss format? And start counting when accumulated power is higher than 0? I have no idea how to make it in Excel but I can make it in few lines in Python. How about if such column was already in CSV?

**Comment by Razor512** [comment]
That would be easier as the values could be directly used with no special macros. It helps when determining how long a device took to charge without having the few seconds of results generated when powering on the UM25C and getting the Bluetooth connected before finally connecting the load.

Usually the point I look for the load is connected which is typically indicated by the resistance not being maxed out, and then using that as the 0 point to start counting up from.

For example when I get a CSV like this, I add offsets where needed to ensure that accumulated time is starting from 0 at the moment the load is connected.
![load-start](https://user-images.githubusercontent.com/75226214/132083245-ce9084a7-fd4b-4411-80f4-201c18e5254e.jpg)

**Comment by kolinger** [comment]
Accumulated time is taken from meter itself. So I didn't modify this time and added new columns named "Run time" and "Run time (seconds)" instead. And these times starts when resistance drops bellow 9999.9 Ω. This counter is based on real time (column "Time") not "Accumulated time" since TC66C doesn't report accumulated time. 

If resistance raises to 9999.9 Ω and drops bellow again timer will **not** reset. I'm not sure if it should reset or not. Most people likely won't measure multiple measurements in one session so it probably doesn't matter. Also glitch/bad contact would reset timer and that would not be desirable. So when this timer starts it will continue with same offset until end of session.

![Screenshot_3](https://user-images.githubusercontent.com/1590930/132086033-eec7744f-8855-4991-8d22-08d700578edf.png)

Does this solve your need?

BTW: Feel free to create another issue for different discussion next time. Hijacking other issues is not good practice.

**Comment by Razor512** [comment]
That would work great. 
Sorry for hijacking the other issue, new to using the site.

**Comment by kolinger** [comment]
You can try with new version. Download [here](https://github.com/kolinger/rd-usb/releases).

**Comment by kolinger** [comment]
Closing this since all brought up suggestions were resolved in new version. If you have any other suggestion feel free to create another issue.
