### ISSUE TITLE
[Feature Request] Live Screen without logging

### ISSUE THREAD

**Issue by Bluscream** [kolinger/rd-usb#27]
I'd like to stream the webui with OBS without the need to start a logging session that i have to delete afterwards anyway. So a live view of all Data without needing to create session would be nice

**Comment by kolinger** [comment]
If you still need this let me know how would you like to switch between logging and just preview. There is no much space for this action in the UI. I could add this as option in settings. What do you think?

**Comment by Bluscream** [comment]
i'd think the non-logging view should be running all the time (would require (re)-connect functionality) and logging should be toggable optionally

**Comment by kolinger** [comment]
I don't think this would be good since you can run this application just to review older data and not have your meter handy. This would result in unexpected connection errors. You need to connect manually even for preview since application doesn't have the ability to know if you meter is available or not. Also you can have multiple meters and then you need to select what you want to use.

This is why I think this should be done as option somewhere where you say - I just want preview - and then connect using Connect button normally.
