### ISSUE TITLE
Sometimes measurements go crazy..

### ISSUE THREAD

**Issue by bursoft-git** [kolinger/rd-usb#4]
I measured the battery charging parameters. Everything was going fine ..
![Wired Quick PB](https://user-images.githubusercontent.com/7475720/56563790-44d7f380-65b5-11e9-81c0-03bc92d86bc0.png)
But when I turned on the screen in the tester, the readings in the WEB-GUI became absolutely wrong. At the same time on the tester screen were normal readings.
![Screenshot_2019-04-21 RD-USB(2)](https://user-images.githubusercontent.com/7475720/56563923-9aac9b80-65b5-11e9-943f-1b44b68e97fc.png)
![Screenshot_2019-04-21 RD-USB(3)](https://user-images.githubusercontent.com/7475720/56563931-9f714f80-65b5-11e9-98fe-e3b8e937a9e8.png)
After disconnect and reconnect to the tester, the readings again became normal.
Here is the log at the time of failure indications
<img width="1280" alt="log" src="https://user-images.githubusercontent.com/7475720/56564204-3938fc80-65b6-11e9-8a83-510be761ba35.png">
![Screenshot_2019-04-21 RD-USB(1)](https://user-images.githubusercontent.com/7475720/56564212-3dfdb080-65b6-11e9-8da8-3c1140955c65.png)
Such failures have happened several times in the last month, this time when the tester’s screen is turned on, and sometimes for no apparent reason. I tried different versions of rd-usb (1.0.0-beta, 1.0.0-alpha.3, 1.0.0-alpha.2), all of them are subject to this error.

Thanks for the great web GUI!

**Comment by kolinger** [comment]
Application doesn't have any ability to corrupt data like this. Parser will work always wrong, not at all or always right. This changes from right to wrong on it's own. So this is what the meter actually reports over bluetooth. But why?

I did see similar issues. Few times insane values like this or more likely no values at all. When I did touch meter it did fix or brake. Turns out that my problem was in meter itself. Bluetooth module in UM34C is connected via few springy contacts (I guess this will be the same for all UM meters with bluetooth). These pads loose connection randomly. I guess because of oxidation. I did take meter apart. Scraped contacts on pcb/springy contacts little bit and then it went away.

When you press button or plug/unplug you will touch pcb and contacts inside move tiny bit and make/or brake connection with bluetooth module. These pins carry power and tx/rx. Probably TX or RX pins gets bad connection and then bluetooth board sends corrupted values away. This will explain your issues and also why you see these weird values only in GUI when screen shows correct values.  

I don't see any way how this can happen otherwise. For confirmation you can use official bluetooth app from RD and you should see exactly same values as in GUI. But since this happens randomly it takes long time to capture. In my case official app did report same nonsense as my application.

I can implement workaround for these nonsense values to drop them but then you will lose measurements. This will only hide errors. It will not solve the problem.

**Comment by bursoft-git** [comment]
Indeed, the contacts may be oxidized. I'll clean them and check. Thank!

**Comment by kolinger** [comment]
Did you solve it or made any progress?

**Comment by bursoft-git** [comment]
I cleaned the contacts and made several measurements, the error no longer repeated

**Comment by kolinger** [comment]
Great. This may help others. Seems like issue with this construction.
